### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by IZOcC** [rogeraabbccdd/Warmod-Plus#11]
How i get the token ?

**Comment by rogeraabbccdd** [comment]
https://github.com/rogeraabbccdd/Warmod-Plus/wiki/Install-&-Configure#web-server

**Comment by IZOcC** [comment]
![demo](https://user-images.githubusercontent.com/24228231/97868869-2067e600-1d19-11eb-9074-3db063452d36.PNG)
when you click on add a new token nothing happens
