### ISSUE TITLE
Requirement extension might be outdated 

### ISSUE THREAD

**Issue by GTAmama16** [rogeraabbccdd/Warmod-Plus#2]
so was trying to compile the plugins , but keep getting error when im pretty sure that i install everything, but it keep showing error when compiling, was thinking is it the requirement are outdated ?

**Comment by rogeraabbccdd** [comment]
@GTAmama16 please check your include files
![Code_xVEaXcmsHr](https://user-images.githubusercontent.com/15815422/66440132-89245680-ea64-11e9-81d8-c83f831ea9ca.png
