### ISSUE TITLE
discord server is gone

### ISSUE THREAD

**Issue by udee297** [rogeraabbccdd/Warmod-Plus#7]
i was already on the discord but not its missing from my server list

**Comment by rogeraabbccdd** [comment]
I have deleted the discord server.
People keep asking me dumb questions, I don't know why they didn't try to search the answer first and use their brain before asking questions.
It's really annoying and I'm tired of these people.

**Comment by udee297** [comment]
Oh its too bad.. i can find any answer just by using search function haha
